name: null
#nesterov: False # only applicable for SGD
#learning_rate: null
#weight_decay: null
#momentum: 0.9
args:
  lr: null
  weight_decay: null

freeze_layers: null
epochs: null
loss_weight_type: null
lr_warmup:
  epochs: 0
  multiplier: null
lr_scheduler:
  type: null
temperature: 1.0
grad_clip: null